
//int age;
//String gender;
//String profession;
//String phoneNumber;
//String nid;
//String migrant;
//String isContacted;
//String isAnyoneInFamily;
//List <DateTime> date;
//String breathCount;
//String fever;
//List<dynamic> symptoms;
//String location;
//List<dynamic> riskGroup;
//int temp;
//String isInfected;
//int interaction;

String location;
String notSelf;
String fullName;
String phoneNumber;
String nid;
String passportID;
String gender;
String age;
String fever;
String coughOrThroatPain;
String problemBreathing;
String cameBackFromAbroad;
String contactWithAnyCOVIDPatient;
String anyoneCloseWithSymptoms;
String cameInContactWithPersonHavingCoughOrThroatPain;
String riskGroup;
